### ISSUE TITLE
Derivative Calculation Mistake

### ISSUE THREAD

**Issue by alexandroslessis** [dgorissen/naca#3]
I think there is a minus missing in the derivative calculation in line 238 (naca5) of naca.py. Without fixing, if the number of points is too large, a discontinuity appears in the max camber location.

**Comment by dgorissen** [comment]
Apologies I missed this somehow. Probably too long ago but still happy to take a PR if you recall the fix

**Comment by alexandroslessis** [comment]
I think the derivative variable dyc2_dx estimation should have a minus sign in front. Take a look at the naca 5 digit airfoil calculation here: http://airfoiltools.com/airfoil/naca5digit

Here is a screenshot of the formulae used:
![derivative_naca5](https://user-images.githubusercontent.com/40567912/149578998-2b08860a-a83c-4ac5-8276-4952dd0b4028.png)
